backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# publish_mode: editorial_workflow

media_folder: "public/images/uploads" # Media files will be stored here
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with this

collections:

  - label: "Projects"
    label_singular: "Project"
    name: "projects"
    folder: "src/pages"
    create: true

    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../../layouts/ProjectLayout.astro"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}

  - label: "People" # Used in the UI
    label_singular: "Person"
    name: "people" # Used in routes, e.g., /admin/collections/blog
    folder: "src/pages" # The path to the folder where the documents are stored
    filter: {field: "category", value: "{{name}}"}
    path: "{{project}}/{{name}}/{{slug}}"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    preview_path: "src/pages/{{project}}/{{name}}/{{slug}}"
    view_groups: 
      - label: Project
        field: project
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../../layouts/PostLayout.astro"}
      - {label: "Category", name: "category", widget: "hidden", default: "{{label}}"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Search Terms", name: "searchTerms", widget: "list"}

      - label: "Project"
        name: "project"
        widget: "relation"
        collection: "projects"
        search_fields: ["title"]
        value_field: "title"
        
      - label: "Details"
        name: "details"
        widget: "object"
        required: false
        fields:
          - label: "Aliases"
            name: "aliases"
            widget: "list"
            field: {label: "Alias", name: "alias", widget: "string", required: false}
          - {label: "Age", name: "age", widget: "string", required: false}
          - {label: "Birthplace", name: "birthplace", widget: "string", required: false}
          - {label: "Primary Residence", name: "residence", widget: "string", required: false}
          - {label: "Species", name: "species", widget: "string", required: false}
          - {label: "Gender Identity", name: "gender", widget: "string", required: false}
          - label: "Professions"
            name: "professions"
            widget: "list"
            field: {label: "Profession", name: "profession", widget: "string", required: false}

      - label: "Connections"
        name: "connections"
        widget: "object"
        required: false
        fields:
          - label: "Family"
            name: "family"
            widget: "list"
            summary: '{{fields.relationship}} - {{fields.name}}'
            fields:
              - {label: "Relationship", name: "relationship", widget: "string", required: false}
              - {label: "Name", name: "name", widget: "string", required: false}
          - label: "Romantic Partners"
            name: "romances"
            widget: "list"
            field: {label: "Partner", name: "partner", widget: "string", required: false}
          - label: "Affiliations"
            name: "affilitations"
            widget: "list"
            field: {label: "Group", name: "group", widget: "string", required: false}
