backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# publish_mode: editorial_workflow

media_folder: "public/images/uploads" # Media files will be stored here
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with this

site_url: "https://tome.nowickidesign.com"
display_url: "https://tome.nowickidesign.com"

collections:

  - label: "Projects"
    label_singular: "Project"
    name: "projects"
    folder: "src/pages"
    create: true

    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../../layouts/ArticleListLayout.astro"}
      - {label: "Title", name: "title", widget: "string", pattern: [".{1,40}", "Must be no longer than 40 characters"],}
      - {label: "Description", name: "description", widget: "markdown", pattern: [".{1,120}", "Must be no longer than 120 characters"]}
      - {label: "Year Notation", name: "yearNotation", widget: "string"}

  - label: "People"
    label_singular: "Person"
    name: "people"
    folder: "src/pages"
    filter: {field: "category", value: "People"}
    path: "{{project}}/people/{{slug}}"
    create: true
    slug: "{{slug}}"
    view_groups: 
      - label: Project
        field: project
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../../layouts/PostLayout.astro"}
      - label: "Project"
        name: "project"
        widget: "relation"
        collection: "projects"
        search_fields: ["title"]
        value_field: "title"
      - {label: "Category", name: "category", widget: "hidden", default: "People"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string", pattern: [".{1,120}", "Must be no longer than 120 characters"], required: false}
      - label: "Search Terms"
        label_singular: "Search Term"
        name: "searchTerms"
        widget: "list"
        summary: "{{fields.searchTerm}}"
        field: {label: "Search Term", name: "searchTerm", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
       
      - label: "Details"
        name: "details"
        widget: "object"
        required: false
        fields:
          - label: "Aliases"
            label_singular: "Alias"
            name: "aliases"
            widget: "list"
            summary: "{{fields.alias}}"
            field: {label: "Alias", name: "alias", widget: "string"}
          - {label: "Birthplace", name: "birthplace", widget: "string", required: false}
          - {label: "Primary Residence", name: "residence", widget: "string", required: false}
          - {label: "Species", name: "species", widget: "string", required: false}
          - {label: "Gender Identity", name: "gender", widget: "string", required: false}
          - label: "Professions"
            label_singular: "Profession"
            name: "professions"
            widget: "list"
            summary: "{{fields.profession}}"
            field: {label: "Profession", name: "profession", widget: "string"}

      - label: "Connections"
        name: "connections"
        widget: "object"
        required: false
        fields:
          - label: "Family"
            label_singular: "Member"
            name: "family"
            widget: "list"
            summary: "{{fields.relationship}} - {{fields.name}}"
            fields:
              - {label: "Relationship", name: "relationship", widget: "string"}
              - {label: "Name", name: "name", widget: "string"}
          - label: "Romantic Partners"
            label_singular: "Partner"
            name: "romances"
            widget: "list"
            summary: "{{fields.partner}}"
            field: {label: "Partner", name: "partner", widget: "string"}
          - label: "Affiliations"
            label_singular: "Affiliation"
            name: "affilitations"
            widget: "list"
            summary: "{{fields.group}}"
            field: {label: "Group", name: "group", widget: "string"}

      - label: "Notable Events"
        label_singular: "Event"
        name: "events"
        widget: "list"
        required: false
        summary: "{{fields.date.year}} - {{fields.title}}"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string", required: false}
          - label: "Date" 
            name: "date"
            widget: "object"
            summary: "{{fields.year}}"
            fields:
              - {label: "Year", name: "year", widget: "number"}
              - {label: "Month - Numerical", name: "month", widget: "number", required: false}
              - {label: "Day - Numerical", name: "day", widget: "number", required: false}
              - {label: "Year Notation", name: "yearNotation", widget: "string", required: false}


  - label: "Groups"
    label_singular: "Group"
    name: "groups"
    folder: "src/pages"
    filter: {field: "category", value: "Groups"}
    path: "{{project}}/groups/{{slug}}"
    create: true
    slug: "{{slug}}"
    view_groups: 
      - label: Project
        field: project
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../../layouts/PostLayout.astro"}
      - label: "Project"
        name: "project"
        widget: "relation"
        collection: "projects"
        search_fields: ["title"]
        value_field: "title"
      - {label: "Category", name: "category", widget: "hidden", default: "Groups"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string", pattern: [".{1,120}", "Must be no longer than 120 characters"], required: false}
      - label: "Search Terms"
        label_singular: "Search Term"
        name: "searchTerms"
        widget: "list"
        summary: "{{fields.searchTerm}}"
        field: {label: "Search Term", name: "searchTerm", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}

      - label: "Details"
        name: "details"
        widget: "object"
        required: false
        fields:
          - {label: "Founding Date", name: "foundingDate", widget: "string", required: false}
          - {label: "Membership Size", name: "membershipSize", widget: "string", required: false}
          - {label: "Organizational Structure", name: "orgStructure", widget: "string", required: false}
          - {label: "Territory", name: "territory", widget: "string", required: false}
          - label: "Notable Members"
            label_singular: "Member"
            name: "notableMembers"
            widget: "list"
            summary: "{{fields.role}} - {{fields.name}}"
            required: false
            fields:
              - {label: "Role", name: "role", widget: "string", required: false}
              - {label: "Name", name: "name", widget: "string"}

      - label: "Connections"
        name: "connections"
        widget: "object"
        required: false
        fields:
          - label: "Allies"
            label_singular: "Ally"
            name: "allies"
            widget: "list"
            summary: "{{fields.relationship}} - {{fields.name}}"
            required: false
            fields:
              - {label: "Relationship", name: "relationship", widget: "string", required: false}
              - {label: "Name", name: "name", widget: "string"}
          - label: "Rivals"
            label_singular: "Rival"
            name: "rivals"
            widget: "list"
            summary: "{{fields.relationship}} - {{fields.name}}"
            required: false
            fields:
              - {label: "Relationship", name: "relationship", widget: "string", required: false}
              - {label: "Name", name: "name", widget: "string"}

      - label: "Notable Events"
        label_singular: "Event"
        name: "events"
        widget: "list"
        required: false
        summary: "{{fields.title}}"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string", required: false}
          - label: "Date" 
            name: "date"
            widget: "object"
            summary: "{{fields.year}}"
            fields:
              - {label: "Year", name: "year", widget: "number"}
              - {label: "Month - Numerical", name: "month", widget: "number", required: false}
              - {label: "Day - Numerical", name: "day", widget: "number", required: false}
              - {label: "Year Notation", name: "yearNotation", widget: "string", required: false}

  - label: "Places"
    label_singular: "Place"
    name: "places"
    folder: "src/pages"
    filter: {field: "category", value: "Places"}
    path: "{{project}}/places/{{slug}}"
    create: true
    slug: "{{slug}}"
    view_groups: 
      - label: Project
        field: project
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../../layouts/PostLayout.astro"}
      - label: "Project"
        name: "project"
        widget: "relation"
        collection: "projects"
        search_fields: ["title"]
        value_field: "title"
      - {label: "Category", name: "category", widget: "hidden", default: "Places"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string", pattern: [".{1,120}", "Must be no longer than 120 characters"], required: false}
      - label: "Search Terms"
        label_singular: "Search Term"
        name: "searchTerms"
        widget: "list"
        summary: "{{fields.searchTerm}}"
        field: {label: "Search Term", name: "searchTerm", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}

      - label: "Details"
        name: "details"
        widget: "object"
        required: false
        fields:
          - {label: "Location", name: "location", widget: "string", required: false}
          - {label: "Population", name: "population", widget: "string", required: false}
          - label: "Landmarks"
            label_singular: "Landmark"
            name: "landmarks"
            widget: "list"
            summary: "{{fields.name}}"
            required: false
            fields:
              - {label: "Location", name: "location", widget: "string", required: false}
              - {label: "Name", name: "name", widget: "string"}
          - label: "Notable Residents"
            label_singular: "Resident"
            name: "notableResidents"
            widget: "list"
            summary: "{{fields.name}}"
            required: false
            field: {label: "Name", name: "name", widget: "string"}
          - label: "Notable Groups"
            label_singular: "Group"
            name: "notableGroups"
            widget: "list"
            summary: "{{fields.name}}"
            required: false
            field: {label: "Name", name: "name", widget: "string"}

      - label: "Notable Events"
        label_singular: "Event"
        name: "events"
        widget: "list"
        required: false
        summary: "{{fields.title}}"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string", required: false}
          - label: "Date" 
            name: "date"
            widget: "object"
            summary: "{{fields.year}}"
            fields:
              - {label: "Year", name: "year", widget: "number"}
              - {label: "Month - Numerical", name: "month", widget: "number", required: false}
              - {label: "Day - Numerical", name: "day", widget: "number", required: false}
              - {label: "Year Notation", name: "yearNotation", widget: "string", required: false}


  - label: "Events"
    label_singular: "Event"
    name: "events"
    folder: "src/pages"
    filter: {field: "category", value: "Events"}
    path: "{{project}}/events/{{slug}}"
    create: true
    slug: "{{slug}}"
    view_groups: 
      - label: Project
        field: project
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../../layouts/PostLayout.astro"}
      - label: "Project"
        name: "project"
        widget: "relation"
        collection: "projects"
        search_fields: ["title"]
        value_field: "title"
      - {label: "Category", name: "category", widget: "hidden", default: "Events"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string", pattern: [".{1,120}", "Must be no longer than 120 characters"], required: false}
      - label: "Search Terms"
        label_singular: "Search Term"
        name: "searchTerms"
        widget: "list"
        summary: "{{fields.searchTerm}}"
        field: {label: "Search Term", name: "searchTerm", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}

      - label: "Details"
        name: "details"
        widget: "object"
        required: false
        fields:
          - label: "Start Date" 
            name: "startDate"
            widget: "object"
            summary: "{{fields.year}}"
            fields:
              - {label: "Label", name: "label", widget: "hidden", default: "Start Date"}
              - {label: "Year", name: "year", widget: "number", required: false}
              - {label: "Month - Numerical", name: "month", widget: "number", required: false}
              - {label: "Day - Numerical", name: "day", widget: "number", required: false}
              - {label: "Year Notation", name: "yearNotation", widget: "string", required: false}
          - label: "End Date" 
            name: "endDate"
            widget: "object"
            summary: "{{fields.year}}"
            required: false
            fields:
              - {label: "Year", name: "year", widget: "number", required: false}
              - {label: "Month - Numerical", name: "month", widget: "number", required: false}
              - {label: "Day - Numerical", name: "day", widget: "number", required: false}
              - {label: "Year Notation", name: "yearNotation", widget: "string", required: false}
          - {label: "Location", name: "location", widget: "string", required: false}
          - label: "Notable Participants"
            label_singular: "Participant"
            name: "notableParticipants"
            widget: "list"
            summary: "{{fields.name}}"
            required: false
            field: {label: "Name", name: "name", widget: "string"}
          - label: "Notable Groups"
            label_singular: "Group"
            name: "notableGroups"
            widget: "list"
            summary: "{{fields.name}}"
            required: false
            field: {label: "Name", name: "name", widget: "string"}

      - label: "Contributing Events"
        label_singular: "Event"
        name: "events"
        widget: "list"
        required: false
        summary: "{{fields.title}}"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string", required: false}
          - label: "Date" 
            name: "date"
            widget: "object"
            summary: "{{fields.year}}"
            fields:
              - {label: "Year", name: "year", widget: "number"}
              - {label: "Month - Numerical", name: "month", widget: "number", required: false}
              - {label: "Day - Numerical", name: "day", widget: "number", required: false}
              - {label: "Year Notation", name: "yearNotation", widget: "string", required: false}


  - label: "Things"
    label_singular: "Things"
    name: "things"
    folder: "src/pages"
    filter: {field: "category", value: "Things"}
    path: "{{project}}/things/{{slug}}"
    create: true
    slug: "{{slug}}"
    view_groups: 
      - label: Project
        field: project
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../../layouts/PostLayout.astro"}
      - label: "Project"
        name: "project"
        widget: "relation"
        collection: "projects"
        search_fields: ["title"]
        value_field: "title"
      - {label: "Category", name: "category", widget: "hidden", default: "Things"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string", pattern: [".{1,120}", "Must be no longer than 120 characters"], required: false}
      - label: "Search Terms"
        label_singular: "Search Term"
        name: "searchTerms"
        widget: "list"
        summary: "{{fields.searchTerm}}"
        field: {label: "Search Term", name: "searchTerm", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}

      - label: "Notable Events"
        label_singular: "Event"
        name: "events"
        widget: "list"
        required: false
        summary: "{{fields.title}}"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string", required: false}
          - label: "Date" 
            name: "date"
            widget: "object"
            summary: "{{fields.year}}"
            fields:
              - {label: "Year", name: "year", widget: "number"}
              - {label: "Month - Numerical", name: "month", widget: "number", required: false}
              - {label: "Day - Numerical", name: "day", widget: "number", required: false}
              - {label: "Year Notation", name: "yearNotation", widget: "string", required: false}
